services:
  - type: web
    name: crowdvision-ai
    env: python
    region: frankfurt
    branch: main
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=10000 app:app
    plan: free
